import path from "path";
import { fileURLToPath } from "url";
import type { CollectionConfig } from "payload";
import { isAdmin, isStaff, publicRead } from "@backend/payload/access";

const dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Uploads — the collection that makes the admin real. Until it exists the
 * client cannot put a photograph of her own work on her own website
 * (docs/DATABASE.md §3).
 *
 * ⚠ STORAGE IS NOT YET CHOSEN. With no adapter configured, Payload writes
 * files to the local filesystem. That is correct for local development and
 * WRONG on Vercel, whose filesystem is ephemeral: uploads survive until the
 * next deployment and then vanish silently (docs/DEPLOYMENT.md §4).
 *
 * Before ANY real client photography is uploaded, or this is deployed, a
 * storage adapter must be added — Cloudflare R2 or Vercel Blob. Swapping
 * the adapter is a config change, not a schema change, so nothing here has
 * to be redesigned. `next.config.ts` images.remotePatterns must gain the
 * chosen host at the same time or every image on the site breaks.
 */
export const Media: CollectionConfig = {
  slug: "media",
  admin: {
    group: "Shop",
    useAsTitle: "alt",
    description: "Photography for products and occasions.",
    defaultColumns: ["filename", "alt", "updatedAt"],
  },
  access: {
    /* Images on a public shop are public by definition. Nothing private
       may ever be stored here — receipts and documents stream through an
       authenticated route instead (docs/DATABASE.md §3). */
    read: publicRead,
    create: isStaff,
    update: isStaff,
    delete: isAdmin,
  },
  upload: {
    /* Explicit, and outside src/. Payload's default would write uploads
       into the source tree. This directory is gitignored — see the storage
       warning above; it is development-only. */
    staticDir: path.resolve(dirname, "../../uploads"),
    mimeTypes: ["image/jpeg", "image/png", "image/webp", "image/avif"],
    /* Generated by sharp, which is already a dependency. Sizes match the
       storefront's real breakpoints rather than arbitrary round numbers. */
    imageSizes: [
      { name: "thumbnail", width: 400, height: undefined, position: "centre" },
      { name: "card", width: 800, height: undefined, position: "centre" },
      { name: "hero", width: 1600, height: undefined, position: "centre" },
      { name: "og", width: 1200, height: 630, position: "centre" },
    ],
    focalPoint: true,
  },
  fields: [
    {
      name: "alt",
      type: "text",
      required: true,
      /* Required, not suggested. Alt text is how a screen-reader user and
         a search engine both perceive the photograph; making it optional
         guarantees it is skipped. */
      admin: {
        description:
          "Describe the arrangement for someone who cannot see it, e.g. 'Blush peonies in a cream vase'.",
      },
    },
    {
      name: "credit",
      type: "text",
      admin: { description: "Photographer attribution, if required." },
    },
  ],
};
