import path from "path";
import { fileURLToPath } from "url";
import type { CollectionConfig } from "payload";
import { isAdmin, isStaff, publicRead } from "@backend/payload/access";

const dirname = path.dirname(fileURLToPath(import.meta.url));

/**
 * Uploads — the collection that makes the admin real. Without it the client
 * cannot put a photograph of her own work on her own website
 * (docs/DATABASE.md §3).
 *
 * STORAGE: Vercel Blob in production, configured in
 * backend/payload/storage.ts and wired in payload.config.ts. The
 * `staticDir` below is the LOCAL DEVELOPMENT fallback, used only when
 * BLOB_READ_WRITE_TOKEN is absent; production refuses to boot without the
 * token rather than quietly writing to an ephemeral disk.
 *
 * PUBLIC BY DESIGN. Vercel Blob supports public access only, and product
 * photography is public anyway. Nothing private may ever be stored here —
 * receipts and documents stream through an authenticated route instead.
 */
export const Media: CollectionConfig = {
  slug: "media",
  admin: {
    group: "Shop",
    useAsTitle: "alt",
    description: "Photography for products and occasions.",
    defaultColumns: ["filename", "alt", "updatedAt"],
  },
  access: {
    /* Images on a public shop are public by definition. Nothing private
       may ever be stored here — receipts and documents stream through an
       authenticated route instead (docs/DATABASE.md §3). */
    read: publicRead,
    create: isStaff,
    update: isStaff,
    delete: isAdmin,
  },
  upload: {
    /* LOCAL DEVELOPMENT FALLBACK ONLY. Ignored once the Vercel Blob adapter
       is active. Explicit, and outside src/, because Payload's default would
       write uploads into the source tree. Gitignored. */
    staticDir: path.resolve(dirname, "../../uploads"),
    /* Allow-list, not a block-list. An SVG is a script container and is
       deliberately excluded; so is anything that is not an image. Payload
       also sniffs the real type, so renaming a .svg to .jpg does not pass. */
    mimeTypes: ["image/jpeg", "image/png", "image/webp", "image/avif"],
    /* Generated by sharp, which is already a dependency. Sizes match the
       storefront's real breakpoints rather than arbitrary round numbers. */
    imageSizes: [
      { name: "thumbnail", width: 400, height: undefined, position: "centre" },
      { name: "card", width: 800, height: undefined, position: "centre" },
      { name: "hero", width: 1600, height: undefined, position: "centre" },
      { name: "og", width: 1200, height: 630, position: "centre" },
    ],
    focalPoint: true,
  },
  fields: [
    {
      name: "alt",
      type: "text",
      required: true,
      /* Required, not suggested. Alt text is how a screen-reader user and
         a search engine both perceive the photograph; making it optional
         guarantees it is skipped. */
      admin: {
        description:
          "Describe the arrangement for someone who cannot see it, e.g. 'Blush peonies in a cream vase'.",
      },
    },
    {
      name: "credit",
      type: "text",
      admin: { description: "Photographer attribution, if required." },
    },
  ],
};
