import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/**
 * Discounts: automatic sales and discount codes.
 *
 * Generated by `pnpm migrate:create discounts`, AFTER 20261004_193027_quote_pay_link
 * (the snapshot beside this file is cumulative, so the two must never be
 * generated from the same starting point). Nothing here was written by hand.
 *
 * PURELY ADDITIVE. A new `discounts` table with its two child tables, and new
 * columns on `orders`, `orders_items` and Payload's own lock table. Every new
 * column is nullable or has a default, so existing rows are untouched and the
 * code deployed before this migration keeps working against the new schema.
 *
 * THE ORDER OF A RELEASE IS: run this migration against production, check it,
 * THEN deploy the code. Never the reverse — Payload selects every configured
 * column, so new code against the old schema fails every read and write of
 * `orders`, including the Stripe webhook (docs/PAYMENTS.md).
 *
 * The column names below are relied on, by name, by the one raw statement
 * that counts a code as used: backend/payments/redeem.ts reads
 * orders.coupon_discount_id / orders.coupon_redeemed_at and
 * discounts.times_used / discounts.usage_limit.
 *
 * `discounts.code` is UNIQUE and nullable: Postgres treats NULLs as distinct,
 * so any number of automatic sales share "no code". The collection's hook
 * stores null, never an empty string, for exactly this reason.
 */

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_discounts_categories" AS ENUM('bouquet', 'vase-arrangement', 'box-arrangement', 'basket', 'single-stem', 'plant', 'event-piece');
  CREATE TYPE "public"."enum_discounts_kind" AS ENUM('automatic', 'code');
  CREATE TYPE "public"."enum_discounts_value_type" AS ENUM('percentage', 'fixed');
  CREATE TYPE "public"."enum_discounts_applies_to" AS ENUM('all', 'products', 'occasions', 'categories');
  CREATE TABLE "discounts_categories" (
  	"order" integer NOT NULL,
  	"parent_id" integer NOT NULL,
  	"value" "enum_discounts_categories",
  	"id" serial PRIMARY KEY NOT NULL
  );
  
  CREATE TABLE "discounts" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"title" varchar NOT NULL,
  	"kind" "enum_discounts_kind" NOT NULL,
  	"code" varchar,
  	"value_type" "enum_discounts_value_type" NOT NULL,
  	"percent_off" numeric,
  	"amount_off_fils" numeric,
  	"applies_to" "enum_discounts_applies_to" DEFAULT 'all' NOT NULL,
  	"label_en" varchar,
  	"label_ar" varchar,
  	"starts_at" timestamp(3) with time zone,
  	"ends_at" timestamp(3) with time zone,
  	"active" boolean DEFAULT false,
  	"min_subtotal_fils" numeric,
  	"usage_limit" numeric,
  	"once_per_customer" boolean DEFAULT false,
  	"times_used" numeric DEFAULT 0 NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL
  );
  
  CREATE TABLE "discounts_rels" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"order" integer,
  	"parent_id" integer NOT NULL,
  	"path" varchar NOT NULL,
  	"products_id" integer,
  	"occasions_id" integer
  );
  
  ALTER TABLE "orders_items" ADD COLUMN "compare_at_unit_price_fils" numeric;
  ALTER TABLE "orders_items" ADD COLUMN "sale_label_en" varchar;
  ALTER TABLE "orders_items" ADD COLUMN "sale_label_ar" varchar;
  ALTER TABLE "orders_items" ADD COLUMN "sale_id" integer;
  ALTER TABLE "orders" ADD COLUMN "coupon_discount_id" integer;
  ALTER TABLE "orders" ADD COLUMN "discount_snapshot" jsonb;
  ALTER TABLE "orders" ADD COLUMN "coupon_redeemed_at" timestamp(3) with time zone;
  ALTER TABLE "payload_locked_documents_rels" ADD COLUMN "discounts_id" integer;
  ALTER TABLE "discounts_categories" ADD CONSTRAINT "discounts_categories_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."discounts"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "discounts_rels" ADD CONSTRAINT "discounts_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."discounts"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "discounts_rels" ADD CONSTRAINT "discounts_rels_products_fk" FOREIGN KEY ("products_id") REFERENCES "public"."products"("id") ON DELETE cascade ON UPDATE no action;
  ALTER TABLE "discounts_rels" ADD CONSTRAINT "discounts_rels_occasions_fk" FOREIGN KEY ("occasions_id") REFERENCES "public"."occasions"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "discounts_categories_order_idx" ON "discounts_categories" USING btree ("order");
  CREATE INDEX "discounts_categories_parent_idx" ON "discounts_categories" USING btree ("parent_id");
  CREATE INDEX "discounts_kind_idx" ON "discounts" USING btree ("kind");
  CREATE UNIQUE INDEX "discounts_code_idx" ON "discounts" USING btree ("code");
  CREATE INDEX "discounts_active_idx" ON "discounts" USING btree ("active");
  CREATE INDEX "discounts_updated_at_idx" ON "discounts" USING btree ("updated_at");
  CREATE INDEX "discounts_created_at_idx" ON "discounts" USING btree ("created_at");
  CREATE INDEX "discounts_rels_order_idx" ON "discounts_rels" USING btree ("order");
  CREATE INDEX "discounts_rels_parent_idx" ON "discounts_rels" USING btree ("parent_id");
  CREATE INDEX "discounts_rels_path_idx" ON "discounts_rels" USING btree ("path");
  CREATE INDEX "discounts_rels_products_id_idx" ON "discounts_rels" USING btree ("products_id");
  CREATE INDEX "discounts_rels_occasions_id_idx" ON "discounts_rels" USING btree ("occasions_id");
  ALTER TABLE "orders_items" ADD CONSTRAINT "orders_items_sale_id_discounts_id_fk" FOREIGN KEY ("sale_id") REFERENCES "public"."discounts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "orders" ADD CONSTRAINT "orders_coupon_discount_id_discounts_id_fk" FOREIGN KEY ("coupon_discount_id") REFERENCES "public"."discounts"("id") ON DELETE set null ON UPDATE no action;
  ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_discounts_fk" FOREIGN KEY ("discounts_id") REFERENCES "public"."discounts"("id") ON DELETE cascade ON UPDATE no action;
  CREATE INDEX "orders_items_sale_idx" ON "orders_items" USING btree ("sale_id");
  CREATE INDEX "orders_coupon_discount_idx" ON "orders" USING btree ("coupon_discount_id");
  CREATE INDEX "payload_locked_documents_rels_discounts_id_idx" ON "payload_locked_documents_rels" USING btree ("discounts_id");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "discounts_categories" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "discounts" DISABLE ROW LEVEL SECURITY;
  ALTER TABLE "discounts_rels" DISABLE ROW LEVEL SECURITY;
  DROP TABLE "discounts_categories" CASCADE;
  DROP TABLE "discounts" CASCADE;
  DROP TABLE "discounts_rels" CASCADE;
  ALTER TABLE "orders_items" DROP CONSTRAINT "orders_items_sale_id_discounts_id_fk";
  
  ALTER TABLE "orders" DROP CONSTRAINT "orders_coupon_discount_id_discounts_id_fk";
  
  ALTER TABLE "payload_locked_documents_rels" DROP CONSTRAINT "payload_locked_documents_rels_discounts_fk";
  
  DROP INDEX "orders_items_sale_idx";
  DROP INDEX "orders_coupon_discount_idx";
  DROP INDEX "payload_locked_documents_rels_discounts_id_idx";
  ALTER TABLE "orders_items" DROP COLUMN "compare_at_unit_price_fils";
  ALTER TABLE "orders_items" DROP COLUMN "sale_label_en";
  ALTER TABLE "orders_items" DROP COLUMN "sale_label_ar";
  ALTER TABLE "orders_items" DROP COLUMN "sale_id";
  ALTER TABLE "orders" DROP COLUMN "coupon_discount_id";
  ALTER TABLE "orders" DROP COLUMN "discount_snapshot";
  ALTER TABLE "orders" DROP COLUMN "coupon_redeemed_at";
  ALTER TABLE "payload_locked_documents_rels" DROP COLUMN "discounts_id";
  DROP TYPE "public"."enum_discounts_categories";
  DROP TYPE "public"."enum_discounts_kind";
  DROP TYPE "public"."enum_discounts_value_type";
  DROP TYPE "public"."enum_discounts_applies_to";`)
}
