import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

/*
 * PAYMENT REQUESTS — confirm an enquiry, pay by link, invoice.
 *
 * ADDITIVE ONLY. Every new column is nullable or defaulted, so the code that
 * is live BEFORE this migration keeps working against the new schema. The
 * reverse is not true: code that knows these fields selects them on every
 * orders read, so it must never serve traffic before this has been applied.
 * The order is strictly: migrate production -> verify -> deploy the code.
 *
 * Three blocks below are HAND-ADDED and marked. Everything else is as
 * generated by `pnpm migrate:create quote_pay_link`.
 */
export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_orders_locale" AS ENUM('en', 'ar');
  CREATE TYPE "public"."enum_enquiries_locale" AS ENUM('en', 'ar');
  /* HAND-EDITED (1 of 3): IF NOT EXISTS added to the three generated lines.
     Postgres 12+ allows ADD VALUE inside the migration's transaction as long
     as the new values are not USED in it, which they are not. IF NOT EXISTS
     makes a re-run after a rollback harmless: "down" cannot remove them. */
  ALTER TYPE "public"."enum_email_log_type" ADD VALUE IF NOT EXISTS 'payment-request';
  ALTER TYPE "public"."enum_email_log_type" ADD VALUE IF NOT EXISTS 'payment-received';
  ALTER TYPE "public"."enum_email_log_type" ADD VALUE IF NOT EXISTS 'owner-quote-paid';
  ALTER TABLE "orders" ADD COLUMN "enquiry_id" integer;
  ALTER TABLE "orders" ADD COLUMN "locale" "enum_orders_locale" DEFAULT 'en';
  ALTER TABLE "orders" ADD COLUMN "customer_note" varchar;
  ALTER TABLE "orders" ADD COLUMN "pay_token_salt" varchar;
  ALTER TABLE "orders" ADD COLUMN "pay_token_hash" varchar;
  ALTER TABLE "orders" ADD COLUMN "pay_link_expires_at" timestamp(3) with time zone;
  ALTER TABLE "orders" ADD COLUMN "stripe_payment_intent_id" varchar;
  ALTER TABLE "orders" ADD COLUMN "paid_at" timestamp(3) with time zone;
  ALTER TABLE "orders" ADD COLUMN "invoice_number" varchar;
  ALTER TABLE "orders" ADD COLUMN "vat_rate_bps" numeric DEFAULT 0;
  ALTER TABLE "orders" ADD COLUMN "vat_included_fils" numeric DEFAULT 0;
  ALTER TABLE "enquiries" ADD COLUMN "locale" "enum_enquiries_locale";
  ALTER TABLE "enquiries" ADD COLUMN "build_your_own_indicative_total_fils" numeric;
  ALTER TABLE "orders" ADD CONSTRAINT "orders_enquiry_id_enquiries_id_fk" FOREIGN KEY ("enquiry_id") REFERENCES "public"."enquiries"("id") ON DELETE set null ON UPDATE no action;
  CREATE INDEX "orders_enquiry_idx" ON "orders" USING btree ("enquiry_id");
  CREATE UNIQUE INDEX "orders_pay_token_hash_idx" ON "orders" USING btree ("pay_token_hash");
  CREATE INDEX "orders_stripe_payment_intent_id_idx" ON "orders" USING btree ("stripe_payment_intent_id");
  CREATE INDEX "orders_paid_at_idx" ON "orders" USING btree ("paid_at");
  CREATE UNIQUE INDEX "orders_invoice_number_idx" ON "orders" USING btree ("invoice_number");

  /* HAND-ADDED (2 of 3): the invoice counter.
     Deliberately NOT a sequence. A sequence leaves a gap whenever a
     transaction rolls back, and an invoice series with holes in it is the
     first thing an auditor asks about. One row per year, incremented in the
     same statement that writes the number onto the order
     (src/backend/payments/invoice-number.ts), so a failed claim rolls the
     counter back with it. Payload does not know this table exists. */
  CREATE TABLE IF NOT EXISTS "invoice_counters" (
  	"year" integer PRIMARY KEY,
  	"last_value" integer NOT NULL CHECK ("last_value" >= 0)
  );

  /* HAND-ADDED (3 of 3): one LIVE payment request per enquiry.
     Enforced by the database, so a double click or two florists confirming
     the same enquiry cannot create two payable orders. A cancelled request
     drops out of the index, which is what lets "confirm again" work. */
  CREATE UNIQUE INDEX IF NOT EXISTS "orders_one_live_quote_per_enquiry" ON "orders" ("enquiry_id") WHERE "enquiry_id" IS NOT NULL AND "fulfilment_status" <> 'CANCELLED';`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   /* HAND-ADDED: undo the two hand-added objects first. */
  DROP INDEX IF EXISTS "orders_one_live_quote_per_enquiry";
  DROP TABLE IF EXISTS "invoice_counters";

  ALTER TABLE "orders" DROP CONSTRAINT "orders_enquiry_id_enquiries_id_fk";

  /* HAND-EDITED: the generated "down" rebuilt enum_email_log_type without the
     three new values. That fails the moment one email of those types has been
     logged, and Postgres cannot remove a value from an enum any other way.
     The values are therefore LEFT IN PLACE: they are harmless to older code,
     and "up" adds them with IF NOT EXISTS. */
  DROP INDEX "orders_enquiry_idx";
  DROP INDEX "orders_pay_token_hash_idx";
  DROP INDEX "orders_stripe_payment_intent_id_idx";
  DROP INDEX "orders_paid_at_idx";
  DROP INDEX "orders_invoice_number_idx";
  ALTER TABLE "orders" DROP COLUMN "enquiry_id";
  ALTER TABLE "orders" DROP COLUMN "locale";
  ALTER TABLE "orders" DROP COLUMN "customer_note";
  ALTER TABLE "orders" DROP COLUMN "pay_token_salt";
  ALTER TABLE "orders" DROP COLUMN "pay_token_hash";
  ALTER TABLE "orders" DROP COLUMN "pay_link_expires_at";
  ALTER TABLE "orders" DROP COLUMN "stripe_payment_intent_id";
  ALTER TABLE "orders" DROP COLUMN "paid_at";
  ALTER TABLE "orders" DROP COLUMN "invoice_number";
  ALTER TABLE "orders" DROP COLUMN "vat_rate_bps";
  ALTER TABLE "orders" DROP COLUMN "vat_included_fils";
  ALTER TABLE "enquiries" DROP COLUMN "locale";
  ALTER TABLE "enquiries" DROP COLUMN "build_your_own_indicative_total_fils";
  DROP TYPE "public"."enum_orders_locale";
  DROP TYPE "public"."enum_enquiries_locale";`)
}
