/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    occasions: Occasion;
    products: Product;
    orders: Order;
    events: Event;
    enquiries: Enquiry;
    memberships: Membership;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    occasions: OccasionsSelect<false> | OccasionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    enquiries: EnquiriesSelect<false> | EnquiriesSelect<true>;
    memberships: MembershipsSelect<false> | MembershipsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Customers, staff and owners. One table, separated by role.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Used to address the customer personally.
   */
  firstName?: string | null;
  lastName?: string | null;
  /**
   * Display name, built from the first and last name.
   */
  name?: string | null;
  role: 'admin' | 'staff' | 'customer';
  /**
   * International format, e.g. +971501234567
   */
  phone?: string | null;
  /**
   * Optional. Marketing use still requires consent.
   */
  birthday?: string | null;
  /**
   * Suspended and closed accounts cannot log in.
   */
  accountStatus: 'active' | 'suspended' | 'closed';
  anonymisedAt?: string | null;
  /**
   * Saved delivery addresses. Exactly one is the default.
   */
  addresses?:
    | {
        /**
         * e.g. Home, Office, Mum
         */
        label?: string | null;
        /**
         * Who receives it here. Often not the account holder.
         */
        recipientName?: string | null;
        recipientPhone?: string | null;
        emirate: 'abu-dhabi' | 'dubai' | 'sharjah' | 'ajman' | 'umm-al-quwain' | 'ras-al-khaimah' | 'fujairah';
        /**
         * e.g. Al Reem Island
         */
        area?: string | null;
        street: string;
        apartment?: string | null;
        /**
         * Gate codes, landmarks, when to call.
         */
        deliveryInstructions?: string | null;
        /**
         * Only one address can be the default.
         */
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Products this customer saved. Storefront UI comes later.
   */
  wishlist?: (number | Product)[] | null;
  /**
   * Consent is given by a deliberate action, never by placing an order.
   */
  marketing?: {
    subscribed?: boolean | null;
    consentAt?: string | null;
    source?: ('account' | 'footer' | 'checkout' | 'import') | null;
    unsubscribedAt?: string | null;
  };
  /**
   * Admin only. Never shown to the customer.
   */
  tags?:
    | (
        | 'vip'
        | 'corporate'
        | 'wedding-client'
        | 'event-client'
        | 'wholesale'
        | 'repeat'
        | 'do-not-contact'
        | 'payment-issue'
      )[]
    | null;
  /**
   * Internal only. Never shown to the customer.
   */
  notes?: string | null;
  /**
   * Reference to the payment provider. No card data is stored here.
   */
  stripeCustomerId?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  _verified?: boolean | null;
  _verificationToken?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * The arrangements for sale.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * The name customers see, e.g. Amber Hour.
   */
  name: string;
  /**
   * Page address: /product/<slug>. Generated from the name. Changing it breaks live links and past emails.
   */
  slug: string;
  /**
   * One or two lines for product cards and search results. Max 200 characters.
   */
  shortDescription?: string | null;
  /**
   * The full story on the product page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Amount in fils (AED × 100). 48000 = AED 480.00. This is the price customers pay.
   */
  priceFils: number;
  /**
   * Optional crossed-out 'was' price. Must be higher than the price. Leave empty if not on offer.
   */
  compareAtPriceFils?: number | null;
  /**
   * AED only. Multi-currency is deliberately out of scope (docs/ARCHITECTURE.md §9).
   */
  currency: 'AED';
  /**
   * The shape of the arrangement.
   */
  category: 'bouquet' | 'vase-arrangement' | 'box-arrangement' | 'basket' | 'single-stem' | 'plant' | 'event-piece';
  /**
   * Drives the storefront's flower filter.
   */
  flowers?: ('roses' | 'peonies' | 'orchids' | 'tulips' | 'lilies' | 'wildflowers')[] | null;
  /**
   * Which occasion pages this product appears on.
   */
  occasions?: (number | Occasion)[] | null;
  /**
   * The first image is the one shown on cards and in search results.
   */
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  /**
   * Unticked keeps it off the website entirely. New products start hidden.
   */
  available?: boolean | null;
  /**
   * Shows in the homepage featured row.
   */
  featured?: boolean | null;
  /**
   * Shows in the Best Sellers row.
   */
  bestseller?: boolean | null;
  /**
   * Availability depends on the season — shown with a seasonal note.
   */
  seasonal?: boolean | null;
  /**
   * Tick to enforce a stock count. Most made-to-order arrangements do not.
   */
  trackStock?: boolean | null;
  /**
   * Units on hand. Cannot be negative.
   */
  stock?: number | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * Optional. Falls back to the name and short description.
   */
  seo?: {
    /**
     * Max ~60 characters.
     */
    title?: string | null;
    /**
     * Max ~155 characters shows in full on Google.
     */
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Why someone is buying — birthdays, love, new arrivals.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions".
 */
export interface Occasion {
  id: number;
  name: string;
  /**
   * The page address. Generated from the name; changing it breaks live links.
   */
  slug: string;
  /**
   * The tile image on the occasions grid.
   */
  image?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * Unticked hides it from the website.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photography for products and occasions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the arrangement for someone who cannot see it, e.g. 'Blush peonies in a cream vase'.
   */
  alt: string;
  /**
   * Photographer attribution, if required.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Placed orders. The snapshot is permanent; only fulfilment moves.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Assigned automatically from a Postgres sequence. Never reused.
   */
  orderNumber?: string | null;
  customerType: 'guest' | 'registered';
  /**
   * Empty for guest orders.
   */
  customer?: (number | null) | User;
  customerName: string;
  customerEmail: string;
  customerPhone: string;
  deliveryAddress: string;
  deliveryEmirate: 'abu-dhabi' | 'dubai' | 'sharjah' | 'ajman' | 'umm-al-quwain' | 'ras-al-khaimah' | 'fujairah';
  deliveryDate: string;
  /**
   * As sold to the customer, e.g. "13:00 – 17:00".
   */
  deliveryTimeSlot: string;
  /**
   * Directions the customer gave. Not internal notes.
   */
  deliveryNotes?: string | null;
  /**
   * Empty means the buyer is the recipient.
   */
  recipientName?: string | null;
  recipientPhone?: string | null;
  /**
   * Handwritten onto the card exactly as typed.
   */
  cardMessage?: string | null;
  /**
   * Frozen at checkout. Product name, slug and price are copies — renaming or repricing the product never changes them.
   */
  items: {
    /**
     * Reporting link only. Never read for display or price.
     */
    product?: (number | null) | Product;
    productName: string;
    productSlug: string;
    quantity: number;
    /**
     * Amount in fils (AED × 100). 48000 = AED 480.00. Whole numbers only.
     */
    unitPriceFils: number;
    /**
     * Amount in fils (AED × 100). 48000 = AED 480.00. Whole numbers only.
     */
    lineTotalFils: number;
    /**
     * Size, add-ons, e.g. "Size: Deluxe".
     */
    selectedOptions?:
      | {
          label: string;
          value: string;
          id?: string | null;
        }[]
      | null;
    id?: string | null;
  }[];
  /**
   * Amount in fils (AED × 100). 48000 = AED 480.00. Whole numbers only.
   */
  subtotalFils: number;
  /**
   * Amount in fils (AED × 100). 48000 = AED 480.00. Whole numbers only.
   */
  deliveryFeeFils: number;
  /**
   * Amount in fils (AED × 100). 48000 = AED 480.00. Whole numbers only.
   */
  discountFils: number;
  /**
   * Amount in fils (AED × 100). 48000 = AED 480.00. Whole numbers only.
   */
  totalFils: number;
  currency: 'AED';
  couponCode?: string | null;
  /**
   * Amount in fils (AED × 100). 48000 = AED 480.00. Whole numbers only.
   */
  couponDiscountFils?: number | null;
  /**
   * Where the order is in the workshop.
   */
  fulfilmentStatus: 'NEW' | 'CONFIRMED' | 'PREPARING' | 'READY' | 'OUT_FOR_DELIVERY' | 'DELIVERED' | 'CANCELLED';
  /**
   * Set by the payment provider only. Stays PENDING until Stripe/Tabby is connected.
   */
  paymentStatus: 'PENDING' | 'AUTHORIZED' | 'PAID' | 'FAILED' | 'REFUNDED' | 'PARTIALLY_REFUNDED';
  /**
   * Who is making this.
   */
  assignedStaff?: (number | null) | User;
  /**
   * Internal only. Never sent to the customer.
   */
  internalNotes?: string | null;
  /**
   * Where the order came from, e.g. "web-checkout", "phone".
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Wedding, corporate and large-order requests.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  /**
   * Where the quote is sent.
   */
  email: string;
  /**
   * International format, e.g. +971501234567
   */
  phone: string;
  /**
   * For corporate enquiries. Leave empty for private clients.
   */
  company?: string | null;
  eventType: 'wedding' | 'corporate' | 'birthday' | 'engagement' | 'private' | 'decoration' | 'large-order' | 'other';
  /**
   * Leave empty if the client has not fixed a date.
   */
  eventDate?: string | null;
  /**
   * Venue and emirate, as the client described it.
   */
  eventLocation?: string | null;
  estimatedGuests?: number | null;
  /**
   * What the client says they want to spend, in fils (AED × 100). Optional — many will not say.
   */
  budgetFils?: number | null;
  requestedServices?:
    | (
        | 'bridal-bouquet'
        | 'ceremony'
        | 'centrepieces'
        | 'installation'
        | 'arch'
        | 'buttonholes'
        | 'favours'
        | 'setup'
        | 'teardown'
      )[]
    | null;
  /**
   * What the client asked for, in their own words.
   */
  description: string;
  inspirationImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Where this enquiry has got to.
   */
  status: 'NEW' | 'CONTACTED' | 'QUOTED' | 'CONFIRMED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
  /**
   * Who is answering this.
   */
  assignedStaff?: (number | null) | User;
  /**
   * The quoted total in fils (AED × 100). Admin only.
   */
  quoteAmountFils?: number | null;
  /**
   * Internal only. Never sent to the client.
   */
  internalNotes?: string | null;
  /**
   * The page the enquiry was submitted from. Set by the website.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Every lead: build-your-own, events, memberships, contact, custom requests.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries".
 */
export interface Enquiry {
  id: number;
  /**
   * Assigned automatically from a Postgres sequence. Never reused.
   */
  enquiryNumber?: string | null;
  type: 'BUILD_YOUR_OWN' | 'EVENT' | 'MEMBERSHIP' | 'CONTACT' | 'CUSTOM_REQUEST';
  /**
   * Empty for guest enquiries.
   */
  customer?: (number | null) | User;
  contactName: string;
  contactEmail: string;
  contactPhone?: string | null;
  company?: string | null;
  subject: string;
  /**
   * In the enquirer's own words.
   */
  message?: string | null;
  /**
   * Incomplete requests are expected.
   */
  buildYourOwn?: {
    style?: ('romantic' | 'minimal' | 'wild' | 'structured' | 'luxe' | 'unsure') | null;
    flowers?: ('roses' | 'peonies' | 'orchids' | 'tulips' | 'lilies' | 'wildflowers' | 'florists-choice')[] | null;
    colours?: ('blush' | 'white-cream' | 'burgundy' | 'terracotta' | 'sage' | 'bold' | 'pastel')[] | null;
    size?: ('standard' | 'deluxe' | 'premium' | 'statement') | null;
    quantity?: number | null;
    /**
     * Amount in fils (AED × 100). 48000 = AED 480.00. Whole numbers only.
     */
    budgetFils?: number | null;
    deliveryDate?: string | null;
    deliveryLocation?: string | null;
    cardMessage?: string | null;
    specialInstructions?: string | null;
    inspirationImages?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  /**
   * Link to the Events record, which holds the venue, guest count, services and dates. Not duplicated here.
   */
  relatedEvent?: (number | null) | Event;
  /**
   * Interest only. Submitting this never activates a membership — that requires a Membership record and a payment.
   */
  membership?: {
    /**
     * Always 'interest'. Guarded server-side.
     */
    status?: 'interest' | null;
    preferredPlan?: ('MONTHLY' | 'QUARTERLY' | 'CUSTOM') | null;
    frequency?: ('WEEKLY' | 'FORTNIGHTLY' | 'MONTHLY') | null;
    deliveryPreference?: ('home' | 'office' | 'gift') | null;
    preferredStartDate?: string | null;
    /**
     * Amount in fils (AED × 100). 48000 = AED 480.00. Whole numbers only.
     */
    budgetFils?: number | null;
    notes?: string | null;
  };
  customRequest?: {
    category?:
      | ('unusual-flowers' | 'large-order' | 'special-gift' | 'corporate' | 'last-minute' | 'decoration' | 'other')
      | null;
    description?: string | null;
    /**
     * Amount in fils (AED × 100). 48000 = AED 480.00. Whole numbers only.
     */
    budgetFils?: number | null;
    requestedDate?: string | null;
    attachments?:
      | {
          image: number | Media;
          id?: string | null;
        }[]
      | null;
  };
  status: 'NEW' | 'IN_REVIEW' | 'WAITING_FOR_CUSTOMER' | 'QUOTED' | 'CONVERTED' | 'RESOLVED' | 'SPAM' | 'CANCELLED';
  priority: 'LOW' | 'NORMAL' | 'HIGH' | 'URGENT';
  source: 'WEBSITE' | 'INSTAGRAM' | 'WHATSAPP' | 'PHONE' | 'ADMIN' | 'OTHER';
  /**
   * Unassigned leads are the ones that get dropped.
   */
  assignedStaff?: (number | null) | User;
  /**
   * Drives the 'follow-ups due' view. Cannot be set in the past.
   */
  followUpAt?: string | null;
  resolvedAt?: string | null;
  lastContactedAt?: string | null;
  lastContactMethod?: ('EMAIL' | 'WHATSAPP' | 'PHONE' | 'INSTAGRAM' | 'IN_PERSON') | null;
  /**
   * What was said, and when. Internal only.
   */
  communicationNotes?: string | null;
  /**
   * Internal only. Never shown to the enquirer.
   */
  internalNotes?: string | null;
  /**
   * Set when a membership enquiry becomes a real membership.
   */
  convertedMembership?: (number | null) | Membership;
  updatedAt: string;
  createdAt: string;
}
/**
 * Active and pending subscriptions. Billing is not connected yet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships".
 */
export interface Membership {
  id: number;
  /**
   * A membership always belongs to a registered account.
   */
  customer: number | User;
  plan: 'MONTHLY' | 'QUARTERLY' | 'CUSTOM';
  /**
   * Starts PENDING. Until billing is connected, ACTIVE means a human confirmed payment.
   */
  status: 'PENDING' | 'ACTIVE' | 'PAUSED' | 'CANCELLED' | 'EXPIRED';
  deliveryFrequency: 'WEEKLY' | 'FORTNIGHTLY' | 'MONTHLY';
  /**
   * What this customer pays per delivery, in fils (AED × 100).
   */
  pricePerDeliveryFils?: number | null;
  startDate?: string | null;
  /**
   * Maintained by hand until the billing provider is connected.
   */
  nextBillingDate?: string | null;
  notes?: string | null;
  /**
   * Set by the payment provider. Empty until billing is connected.
   */
  providerCustomerId?: string | null;
  providerSubscriptionId?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'occasions';
        value: number | Occasion;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'enquiries';
        value: number | Enquiry;
      } | null)
    | ({
        relationTo: 'memberships';
        value: number | Membership;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  name?: T;
  role?: T;
  phone?: T;
  birthday?: T;
  accountStatus?: T;
  anonymisedAt?: T;
  addresses?:
    | T
    | {
        label?: T;
        recipientName?: T;
        recipientPhone?: T;
        emirate?: T;
        area?: T;
        street?: T;
        apartment?: T;
        deliveryInstructions?: T;
        isDefault?: T;
        id?: T;
      };
  wishlist?: T;
  marketing?:
    | T
    | {
        subscribed?: T;
        consentAt?: T;
        source?: T;
        unsubscribedAt?: T;
      };
  tags?: T;
  notes?: T;
  stripeCustomerId?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  _verified?: T;
  _verificationToken?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions_select".
 */
export interface OccasionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  sortOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  priceFils?: T;
  compareAtPriceFils?: T;
  currency?: T;
  category?: T;
  flowers?: T;
  occasions?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  available?: T;
  featured?: T;
  bestseller?: T;
  seasonal?: T;
  trackStock?: T;
  stock?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  customerType?: T;
  customer?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  deliveryAddress?: T;
  deliveryEmirate?: T;
  deliveryDate?: T;
  deliveryTimeSlot?: T;
  deliveryNotes?: T;
  recipientName?: T;
  recipientPhone?: T;
  cardMessage?: T;
  items?:
    | T
    | {
        product?: T;
        productName?: T;
        productSlug?: T;
        quantity?: T;
        unitPriceFils?: T;
        lineTotalFils?: T;
        selectedOptions?:
          | T
          | {
              label?: T;
              value?: T;
              id?: T;
            };
        id?: T;
      };
  subtotalFils?: T;
  deliveryFeeFils?: T;
  discountFils?: T;
  totalFils?: T;
  currency?: T;
  couponCode?: T;
  couponDiscountFils?: T;
  fulfilmentStatus?: T;
  paymentStatus?: T;
  assignedStaff?: T;
  internalNotes?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  eventType?: T;
  eventDate?: T;
  eventLocation?: T;
  estimatedGuests?: T;
  budgetFils?: T;
  requestedServices?: T;
  description?: T;
  inspirationImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  status?: T;
  assignedStaff?: T;
  quoteAmountFils?: T;
  internalNotes?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "enquiries_select".
 */
export interface EnquiriesSelect<T extends boolean = true> {
  enquiryNumber?: T;
  type?: T;
  customer?: T;
  contactName?: T;
  contactEmail?: T;
  contactPhone?: T;
  company?: T;
  subject?: T;
  message?: T;
  buildYourOwn?:
    | T
    | {
        style?: T;
        flowers?: T;
        colours?: T;
        size?: T;
        quantity?: T;
        budgetFils?: T;
        deliveryDate?: T;
        deliveryLocation?: T;
        cardMessage?: T;
        specialInstructions?: T;
        inspirationImages?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  relatedEvent?: T;
  membership?:
    | T
    | {
        status?: T;
        preferredPlan?: T;
        frequency?: T;
        deliveryPreference?: T;
        preferredStartDate?: T;
        budgetFils?: T;
        notes?: T;
      };
  customRequest?:
    | T
    | {
        category?: T;
        description?: T;
        budgetFils?: T;
        requestedDate?: T;
        attachments?:
          | T
          | {
              image?: T;
              id?: T;
            };
      };
  status?: T;
  priority?: T;
  source?: T;
  assignedStaff?: T;
  followUpAt?: T;
  resolvedAt?: T;
  lastContactedAt?: T;
  lastContactMethod?: T;
  communicationNotes?: T;
  internalNotes?: T;
  convertedMembership?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberships_select".
 */
export interface MembershipsSelect<T extends boolean = true> {
  customer?: T;
  plan?: T;
  status?: T;
  deliveryFrequency?: T;
  pricePerDeliveryFils?: T;
  startDate?: T;
  nextBillingDate?: T;
  notes?: T;
  providerCustomerId?: T;
  providerSubscriptionId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}