/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    occasions: Occasion;
    products: Product;
    events: Event;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    occasions: OccasionsSelect<false> | OccasionsSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'staff' | 'customer';
  /**
   * International format, e.g. +971501234567
   */
  phone?: string | null;
  addresses?:
    | {
        /**
         * e.g. Home, Office
         */
        label?: string | null;
        line1: string;
        line2?: string | null;
        area?: string | null;
        city: string;
        emirate: 'abu-dhabi' | 'dubai' | 'sharjah' | 'ajman' | 'umm-al-quwain' | 'ras-al-khaimah' | 'fujairah';
        isDefault?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Consent is given by a deliberate action, never by placing an order.
   */
  marketing?: {
    subscribed?: boolean | null;
    consentAt?: string | null;
    source?: ('account' | 'footer' | 'checkout' | 'import') | null;
    unsubscribedAt?: string | null;
  };
  /**
   * Set by the payment provider. Never edited by hand.
   */
  stripeCustomerId?: string | null;
  notes?: string | null;
  anonymisedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Photography for products and occasions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe the arrangement for someone who cannot see it, e.g. 'Blush peonies in a cream vase'.
   */
  alt: string;
  /**
   * Photographer attribution, if required.
   */
  credit?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Why someone is buying — birthdays, love, new arrivals.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions".
 */
export interface Occasion {
  id: number;
  name: string;
  /**
   * The page address. Generated from the name; changing it breaks live links.
   */
  slug: string;
  /**
   * The tile image on the occasions grid.
   */
  image?: (number | null) | Media;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * Unticked hides it from the website.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The arrangements for sale.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * The name customers see, e.g. Amber Hour.
   */
  name: string;
  /**
   * Page address: /product/<slug>. Generated from the name. Changing it breaks live links and past emails.
   */
  slug: string;
  /**
   * One or two lines for product cards and search results. Max 200 characters.
   */
  shortDescription?: string | null;
  /**
   * The full story on the product page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Amount in fils (AED × 100). 48000 = AED 480.00. This is the price customers pay.
   */
  priceFils: number;
  /**
   * Optional crossed-out 'was' price. Must be higher than the price. Leave empty if not on offer.
   */
  compareAtPriceFils?: number | null;
  /**
   * AED only. Multi-currency is deliberately out of scope (docs/ARCHITECTURE.md §9).
   */
  currency: 'AED';
  /**
   * The shape of the arrangement.
   */
  category: 'bouquet' | 'vase-arrangement' | 'box-arrangement' | 'basket' | 'single-stem' | 'plant' | 'event-piece';
  /**
   * Drives the storefront's flower filter.
   */
  flowers?: ('roses' | 'peonies' | 'orchids' | 'tulips' | 'lilies' | 'wildflowers')[] | null;
  /**
   * Which occasion pages this product appears on.
   */
  occasions?: (number | Occasion)[] | null;
  /**
   * The first image is the one shown on cards and in search results.
   */
  images: {
    image: number | Media;
    id?: string | null;
  }[];
  /**
   * Unticked keeps it off the website entirely. New products start hidden.
   */
  available?: boolean | null;
  /**
   * Shows in the homepage featured row.
   */
  featured?: boolean | null;
  /**
   * Shows in the Best Sellers row.
   */
  bestseller?: boolean | null;
  /**
   * Availability depends on the season — shown with a seasonal note.
   */
  seasonal?: boolean | null;
  /**
   * Tick to enforce a stock count. Most made-to-order arrangements do not.
   */
  trackStock?: boolean | null;
  /**
   * Units on hand. Cannot be negative.
   */
  stock?: number | null;
  /**
   * Lower numbers appear first.
   */
  sortOrder?: number | null;
  /**
   * Optional. Falls back to the name and short description.
   */
  seo?: {
    /**
     * Max ~60 characters.
     */
    title?: string | null;
    /**
     * Max ~155 characters shows in full on Google.
     */
    description?: string | null;
    image?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Wedding, corporate and large-order requests.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  /**
   * Where the quote is sent.
   */
  email: string;
  /**
   * International format, e.g. +971501234567
   */
  phone: string;
  /**
   * For corporate enquiries. Leave empty for private clients.
   */
  company?: string | null;
  eventType: 'wedding' | 'corporate' | 'birthday' | 'engagement' | 'private' | 'decoration' | 'large-order' | 'other';
  /**
   * Leave empty if the client has not fixed a date.
   */
  eventDate?: string | null;
  /**
   * Venue and emirate, as the client described it.
   */
  eventLocation?: string | null;
  estimatedGuests?: number | null;
  /**
   * What the client says they want to spend, in fils (AED × 100). Optional — many will not say.
   */
  budgetFils?: number | null;
  requestedServices?:
    | (
        | 'bridal-bouquet'
        | 'ceremony'
        | 'centrepieces'
        | 'installation'
        | 'arch'
        | 'buttonholes'
        | 'favours'
        | 'setup'
        | 'teardown'
      )[]
    | null;
  /**
   * What the client asked for, in their own words.
   */
  description: string;
  inspirationImages?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Where this enquiry has got to.
   */
  status: 'NEW' | 'CONTACTED' | 'QUOTED' | 'CONFIRMED' | 'IN_PROGRESS' | 'COMPLETED' | 'CANCELLED';
  /**
   * Who is answering this.
   */
  assignedStaff?: (number | null) | User;
  /**
   * The quoted total in fils (AED × 100). Admin only.
   */
  quoteAmountFils?: number | null;
  /**
   * Internal only. Never sent to the client.
   */
  internalNotes?: string | null;
  /**
   * The page the enquiry was submitted from. Set by the website.
   */
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'occasions';
        value: number | Occasion;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  addresses?:
    | T
    | {
        label?: T;
        line1?: T;
        line2?: T;
        area?: T;
        city?: T;
        emirate?: T;
        isDefault?: T;
        id?: T;
      };
  marketing?:
    | T
    | {
        subscribed?: T;
        consentAt?: T;
        source?: T;
        unsubscribedAt?: T;
      };
  stripeCustomerId?: T;
  notes?: T;
  anonymisedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  credit?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occasions_select".
 */
export interface OccasionsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  image?: T;
  sortOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  shortDescription?: T;
  description?: T;
  priceFils?: T;
  compareAtPriceFils?: T;
  currency?: T;
  category?: T;
  flowers?: T;
  occasions?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  available?: T;
  featured?: T;
  bestseller?: T;
  seasonal?: T;
  trackStock?: T;
  stock?: T;
  sortOrder?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  company?: T;
  eventType?: T;
  eventDate?: T;
  eventLocation?: T;
  estimatedGuests?: T;
  budgetFils?: T;
  requestedServices?: T;
  description?: T;
  inspirationImages?:
    | T
    | {
        image?: T;
        id?: T;
      };
  status?: T;
  assignedStaff?: T;
  quoteAmountFils?: T;
  internalNotes?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}